services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ui
      - api
  ui:
    # Pulls the API image from your Docker Hub repository
    image: strikeitbroke/nextclimb-ui:${IMAGE_TAG:-latest}
    restart: always
  api:
    # Pulls the API image from your Docker Hub repository
    image: strikeitbroke/nextclimb-api:${IMAGE_TAG:-latest}
    restart: always
    environment:
      - DEBUG=False
